// CppAnonym.idl : CppAnonym の IDL ソース
//

// このファイルは、タイプ ライブラリ (CppAnonym.tlb) およびマーシャリング コードを
// 作成するために MIDL ツールによって処理されます。

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(E21F0F69-633F-45E2-BF2E-0EB2D6F2CE6B),
	version(1.0),
	helpstring("CppAnonym 1.0 タイプ ライブラリ")
]
library CppAnonymLib
{
	importlib("stdole2.tlb");
};
